// Code generated by lister-gen. DO NOT EDIT.

package v1alpha0

// RepositoryListerExpansion allows custom methods to be added to
// RepositoryLister.
type RepositoryListerExpansion interface{}

// RepositoryNamespaceListerExpansion allows custom methods to be added to
// RepositoryNamespaceLister.
type RepositoryNamespaceListerExpansion interface{}

// RepositoryCredentialListerExpansion allows custom methods to be added to
// RepositoryCredentialLister.
type RepositoryCredentialListerExpansion interface{}

// RepositoryCredentialNamespaceListerExpansion allows custom methods to be added to
// RepositoryCredentialNamespaceLister.
type RepositoryCredentialNamespaceListerExpansion interface{}
