// Code generated by lister-gen. DO NOT EDIT.

package v1alpha0

import (
	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RepositoryCredentialLister helps list RepositoryCredentials.
// All objects returned here must be treated as read-only.
type RepositoryCredentialLister interface {
	// List lists all RepositoryCredentials in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha0.RepositoryCredential, err error)
	// RepositoryCredentials returns an object that can list and get RepositoryCredentials.
	RepositoryCredentials(namespace string) RepositoryCredentialNamespaceLister
	RepositoryCredentialListerExpansion
}

// repositoryCredentialLister implements the RepositoryCredentialLister interface.
type repositoryCredentialLister struct {
	listers.ResourceIndexer[*applicationv1alpha0.RepositoryCredential]
}

// NewRepositoryCredentialLister returns a new RepositoryCredentialLister.
func NewRepositoryCredentialLister(indexer cache.Indexer) RepositoryCredentialLister {
	return &repositoryCredentialLister{listers.New[*applicationv1alpha0.RepositoryCredential](indexer, applicationv1alpha0.Resource("repositorycredential"))}
}

// RepositoryCredentials returns an object that can list and get RepositoryCredentials.
func (s *repositoryCredentialLister) RepositoryCredentials(namespace string) RepositoryCredentialNamespaceLister {
	return repositoryCredentialNamespaceLister{listers.NewNamespaced[*applicationv1alpha0.RepositoryCredential](s.ResourceIndexer, namespace)}
}

// RepositoryCredentialNamespaceLister helps list and get RepositoryCredentials.
// All objects returned here must be treated as read-only.
type RepositoryCredentialNamespaceLister interface {
	// List lists all RepositoryCredentials in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha0.RepositoryCredential, err error)
	// Get retrieves the RepositoryCredential from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*applicationv1alpha0.RepositoryCredential, error)
	RepositoryCredentialNamespaceListerExpansion
}

// repositoryCredentialNamespaceLister implements the RepositoryCredentialNamespaceLister
// interface.
type repositoryCredentialNamespaceLister struct {
	listers.ResourceIndexer[*applicationv1alpha0.RepositoryCredential]
}
