dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
filename: '{{.InterfaceName}}.go'
pkgname: mocks
packages:
  github.com/argoproj/argo-cd/v3/notification_controller/controller:
    config:
      template: matryer
    interfaces:
      NotificationController: {}
  github.com/argoproj/argo-cd/v3/applicationset/generators:
    interfaces:
      Generator: {}
  github.com/argoproj/argo-cd/v3/applicationset/services:
    interfaces:
      Repos: {}
  github.com/argoproj/argo-cd/v3/applicationset/services/scm_provider:
    config:
      template-data:
        unroll-variadic: true
      dir: applicationset/services/scm_provider/aws_codecommit/mocks
    interfaces:
      AWSCodeCommitClient: {}
      AWSTaggingClient: {}
  github.com/argoproj/argo-cd/v3/applicationset/utils:
    interfaces:
      Renderer: {}
  github.com/argoproj/argo-cd/v3/commitserver/apiclient:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      Clientset: {}
      CommitServiceClient: {}
  github.com/argoproj/argo-cd/v3/commitserver/commit:
    interfaces:
      RepoClientFactory: {}
  github.com/argoproj/argo-cd/v3/controller/cache:
    interfaces:
      LiveStateCache: {}
  github.com/argoproj/argo-cd/v3/pkg/apiclient/cluster:
    interfaces:
      ClusterServiceServer: {}
  github.com/argoproj/argo-cd/v3/pkg/apiclient/session:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      SessionServiceClient: {}
      SessionServiceServer: {}
  github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha1:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      AppProjectInterface: {}
  github.com/argoproj/argo-cd/v3/reposerver/apiclient:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      RepoServerService_GenerateManifestWithFilesClient: {}
      RepoServerServiceClient: {}
  github.com/argoproj/argo-cd/v3/server/application:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      Broadcaster: {}
  github.com/argoproj/argo-cd/v3/server/extension:
    config:
      template-data:
        unroll-variadic: true
    interfaces:
      ApplicationGetter: {}
      ExtensionMetricsRegistry: {}
      ProjectGetter: {}
      RbacEnforcer: {}
      SettingsGetter: {}
      UserGetter: {}
  github.com/argoproj/argo-cd/v3/util/db:
    interfaces:
      ArgoDB: {}
  github.com/argoproj/argo-cd/v3/util/git:
    interfaces:
      Client: {}
  github.com/argoproj/argo-cd/v3/util/helm:
    interfaces:
      Client: {}
  github.com/argoproj/argo-cd/v3/util/io:
    interfaces:
      TempPaths: {}
  github.com/argoproj/argo-cd/v3/util/notification/argocd:
    config:
      template: matryer
    interfaces:
      Service: {}
  github.com/argoproj/argo-cd/v3/util/workloadidentity:
    interfaces:
      TokenProvider: {}
  github.com/microsoft/azure-devops-go-api/azuredevops/v7/git:
    config:
      dir: applicationset/services/scm_provider/azure_devops/git/mocks
    interfaces:
      Client: {}
