// Code generated by informer-gen. DO NOT EDIT.

package v1alpha0

import (
	internalinterfaces "github.com/argoproj/argo-cd/v3/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Repositories returns a RepositoryInformer.
	Repositories() RepositoryInformer
	// RepositoryCredentials returns a RepositoryCredentialInformer.
	RepositoryCredentials() RepositoryCredentialInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Repositories returns a RepositoryInformer.
func (v *version) Repositories() RepositoryInformer {
	return &repositoryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RepositoryCredentials returns a RepositoryCredentialInformer.
func (v *version) RepositoryCredentials() RepositoryCredentialInformer {
	return &repositoryCredentialInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
