// Code generated by informer-gen. DO NOT EDIT.

package v1alpha0

import (
	context "context"
	time "time"

	apisapplicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	versioned "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned"
	internalinterfaces "github.com/argoproj/argo-cd/v3/pkg/client/informers/externalversions/internalinterfaces"
	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/client/listers/application/v1alpha0"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RepositoryCredentialInformer provides access to a shared informer and lister for
// RepositoryCredentials.
type RepositoryCredentialInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() applicationv1alpha0.RepositoryCredentialLister
}

type repositoryCredentialInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRepositoryCredentialInformer constructs a new informer for RepositoryCredential type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRepositoryCredentialInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRepositoryCredentialInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRepositoryCredentialInformer constructs a new informer for RepositoryCredential type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRepositoryCredentialInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha0().RepositoryCredentials(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha0().RepositoryCredentials(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha0().RepositoryCredentials(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha0().RepositoryCredentials(namespace).Watch(ctx, options)
			},
		},
		&apisapplicationv1alpha0.RepositoryCredential{},
		resyncPeriod,
		indexers,
	)
}

func (f *repositoryCredentialInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRepositoryCredentialInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *repositoryCredentialInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisapplicationv1alpha0.RepositoryCredential{}, f.defaultInformer)
}

func (f *repositoryCredentialInformer) Lister() applicationv1alpha0.RepositoryCredentialLister {
	return applicationv1alpha0.NewRepositoryCredentialLister(f.Informer().GetIndexer())
}
