// Code generated by client-gen. DO NOT EDIT.

package v1alpha0

import (
	context "context"

	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	scheme "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RepositoryCredentialsGetter has a method to return a RepositoryCredentialInterface.
// A group's client should implement this interface.
type RepositoryCredentialsGetter interface {
	RepositoryCredentials(namespace string) RepositoryCredentialInterface
}

// RepositoryCredentialInterface has methods to work with RepositoryCredential resources.
type RepositoryCredentialInterface interface {
	Create(ctx context.Context, repositoryCredential *applicationv1alpha0.RepositoryCredential, opts v1.CreateOptions) (*applicationv1alpha0.RepositoryCredential, error)
	Update(ctx context.Context, repositoryCredential *applicationv1alpha0.RepositoryCredential, opts v1.UpdateOptions) (*applicationv1alpha0.RepositoryCredential, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*applicationv1alpha0.RepositoryCredential, error)
	List(ctx context.Context, opts v1.ListOptions) (*applicationv1alpha0.RepositoryCredentialList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *applicationv1alpha0.RepositoryCredential, err error)
	RepositoryCredentialExpansion
}

// repositoryCredentials implements RepositoryCredentialInterface
type repositoryCredentials struct {
	*gentype.ClientWithList[*applicationv1alpha0.RepositoryCredential, *applicationv1alpha0.RepositoryCredentialList]
}

// newRepositoryCredentials returns a RepositoryCredentials
func newRepositoryCredentials(c *ArgoprojV1alpha0Client, namespace string) *repositoryCredentials {
	return &repositoryCredentials{
		gentype.NewClientWithList[*applicationv1alpha0.RepositoryCredential, *applicationv1alpha0.RepositoryCredentialList](
			"repositorycredentials",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *applicationv1alpha0.RepositoryCredential { return &applicationv1alpha0.RepositoryCredential{} },
			func() *applicationv1alpha0.RepositoryCredentialList {
				return &applicationv1alpha0.RepositoryCredentialList{}
			},
		),
	}
}
