// Code generated by client-gen. DO NOT EDIT.

package v1alpha0

import (
	context "context"

	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	scheme "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RepositoriesGetter has a method to return a RepositoryInterface.
// A group's client should implement this interface.
type RepositoriesGetter interface {
	Repositories(namespace string) RepositoryInterface
}

// RepositoryInterface has methods to work with Repository resources.
type RepositoryInterface interface {
	Create(ctx context.Context, repository *applicationv1alpha0.Repository, opts v1.CreateOptions) (*applicationv1alpha0.Repository, error)
	Update(ctx context.Context, repository *applicationv1alpha0.Repository, opts v1.UpdateOptions) (*applicationv1alpha0.Repository, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, repository *applicationv1alpha0.Repository, opts v1.UpdateOptions) (*applicationv1alpha0.Repository, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*applicationv1alpha0.Repository, error)
	List(ctx context.Context, opts v1.ListOptions) (*applicationv1alpha0.RepositoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *applicationv1alpha0.Repository, err error)
	RepositoryExpansion
}

// repositories implements RepositoryInterface
type repositories struct {
	*gentype.ClientWithList[*applicationv1alpha0.Repository, *applicationv1alpha0.RepositoryList]
}

// newRepositories returns a Repositories
func newRepositories(c *ArgoprojV1alpha0Client, namespace string) *repositories {
	return &repositories{
		gentype.NewClientWithList[*applicationv1alpha0.Repository, *applicationv1alpha0.RepositoryList](
			"repositories",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *applicationv1alpha0.Repository { return &applicationv1alpha0.Repository{} },
			func() *applicationv1alpha0.RepositoryList { return &applicationv1alpha0.RepositoryList{} },
		),
	}
}
