// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha0"
	gentype "k8s.io/client-go/gentype"
)

// fakeRepositories implements RepositoryInterface
type fakeRepositories struct {
	*gentype.FakeClientWithList[*v1alpha0.Repository, *v1alpha0.RepositoryList]
	Fake *FakeArgoprojV1alpha0
}

func newFakeRepositories(fake *FakeArgoprojV1alpha0, namespace string) applicationv1alpha0.RepositoryInterface {
	return &fakeRepositories{
		gentype.NewFakeClientWithList[*v1alpha0.Repository, *v1alpha0.RepositoryList](
			fake.Fake,
			namespace,
			v1alpha0.SchemeGroupVersion.WithResource("repositories"),
			v1alpha0.SchemeGroupVersion.WithKind("Repository"),
			func() *v1alpha0.Repository { return &v1alpha0.Repository{} },
			func() *v1alpha0.RepositoryList { return &v1alpha0.RepositoryList{} },
			func(dst, src *v1alpha0.RepositoryList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha0.RepositoryList) []*v1alpha0.Repository { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha0.RepositoryList, items []*v1alpha0.Repository) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
