// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha0 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha0"
	applicationv1alpha0 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha0"
	gentype "k8s.io/client-go/gentype"
)

// fakeRepositoryCredentials implements RepositoryCredentialInterface
type fakeRepositoryCredentials struct {
	*gentype.FakeClientWithList[*v1alpha0.RepositoryCredential, *v1alpha0.RepositoryCredentialList]
	Fake *FakeArgoprojV1alpha0
}

func newFakeRepositoryCredentials(fake *FakeArgoprojV1alpha0, namespace string) applicationv1alpha0.RepositoryCredentialInterface {
	return &fakeRepositoryCredentials{
		gentype.NewFakeClientWithList[*v1alpha0.RepositoryCredential, *v1alpha0.RepositoryCredentialList](
			fake.Fake,
			namespace,
			v1alpha0.SchemeGroupVersion.WithResource("repositorycredentials"),
			v1alpha0.SchemeGroupVersion.WithKind("RepositoryCredential"),
			func() *v1alpha0.RepositoryCredential { return &v1alpha0.RepositoryCredential{} },
			func() *v1alpha0.RepositoryCredentialList { return &v1alpha0.RepositoryCredentialList{} },
			func(dst, src *v1alpha0.RepositoryCredentialList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha0.RepositoryCredentialList) []*v1alpha0.RepositoryCredential {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha0.RepositoryCredentialList, items []*v1alpha0.RepositoryCredential) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
