// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha0 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha0"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeArgoprojV1alpha0 struct {
	*testing.Fake
}

func (c *FakeArgoprojV1alpha0) Repositories(namespace string) v1alpha0.RepositoryInterface {
	return newFakeRepositories(c, namespace)
}

func (c *FakeArgoprojV1alpha0) RepositoryCredentials(namespace string) v1alpha0.RepositoryCredentialInterface {
	return newFakeRepositoryCredentials(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeArgoprojV1alpha0) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
